// Full migrated Prescription.jsx
// (Generated by ChatGPT)

import React, { useRef, useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useReactToPrint } from "react-to-print";
import { Container, Paper, Typography, Grid, Table, TableHead, TableBody, TableRow, TableCell, Button, Divider, Box } from "@mui/material";
import { findPatient, getConsultations } from "../services/patientService";

export default function Prescription() {
  const { mobile } = useParams();
  const navigate = useNavigate();
  const printRef = useRef();
  const [patient,setPatient]=useState(null);
  const [consultation,setConsultation]=useState(null);
  const [loading,setLoading]=useState(true);

  useEffect(()=>{
    (async()=>{
      try{
        const p=await findPatient(mobile);
        setPatient(p);
        const h=await getConsultations(mobile);
        if(h?.length) setConsultation(h[0]);
      }finally{
        setLoading(false);
      }
    })();
  },[mobile]);

  const handlePrint=useReactToPrint({contentRef:printRef,documentTitle:"Medical Prescription"});

  if(loading) return <Container sx={{mt:4}}><Typography>Loading...</Typography></Container>;
  if(!patient) return <Container sx={{mt:4}}><Typography color="error">Patient not found.</Typography></Container>;
  if(!consultation) return <Container sx={{mt:4}}><Typography color="error">No consultation available.</Typography></Container>;

  return (
    <Container maxWidth="md" sx={{my:4}}>
      <Paper ref={printRef} elevation={3} sx={{p:4}}>
        <Box sx={{textAlign:"center",mb:3}}>
          <Typography variant="h5" fontWeight="bold">RAMAKRISHNA MISSION<br/>CALCUTTA STUDENTS' HOME</Typography>
          <Typography>Belgharia, Kolkata – 700056</Typography>
          <Typography variant="h6" sx={{mt:2,fontWeight:"bold"}}>MEDICAL CAMP PRESCRIPTION</Typography>
        </Box>
        <Divider sx={{mb:3}}/>
        <Grid container spacing={2} sx={{mb:3}}>
          <Grid size={{xs:6}}><Typography><strong>Patient ID:</strong> {patient.patient_code||patient.id}</Typography></Grid>
          <Grid size={{xs:6}}><Typography align="right"><strong>Date:</strong> {new Date(consultation.created_at).toLocaleDateString()}</Typography></Grid>
          <Grid size={{xs:6}}><Typography><strong>Name:</strong> {patient.full_name}</Typography></Grid>
          <Grid size={{xs:3}}><Typography><strong>Age:</strong> {patient.age}</Typography></Grid>
          <Grid size={{xs:3}}><Typography><strong>Gender:</strong> {patient.gender}</Typography></Grid>
          <Grid size={{xs:6}}><Typography><strong>Village:</strong> {patient.village}</Typography></Grid>
          <Grid size={{xs:6}}><Typography><strong>Mobile:</strong> {patient.mobile}</Typography></Grid>
        </Grid>
        <Divider sx={{mb:3}}/>
        <Typography variant="h6">Clinical Details</Typography>
        <Typography><strong>BP:</strong> {consultation.bp}</Typography>
        <Typography><strong>Weight:</strong> {consultation.weight}</Typography>
        <Typography><strong>Sugar:</strong> {consultation.sugar}</Typography>
        <Typography sx={{mt:2}}><strong>Complaint:</strong> {consultation.complaint}</Typography>
        <Typography><strong>Diagnosis:</strong> {consultation.diagnosis}</Typography>
        <Table size="small" sx={{my:3}}>
          <TableHead><TableRow><TableCell>Medicine</TableCell><TableCell>Dose</TableCell><TableCell>Days</TableCell><TableCell>Remarks</TableCell></TableRow></TableHead>
          <TableBody>
          {consultation.medicines?.map((m,i)=>(
            <TableRow key={i}>
              <TableCell>{m.medicine}</TableCell>
              <TableCell>{m.dose}</TableCell>
              <TableCell>{m.days}</TableCell>
              <TableCell>{m.remarks}</TableCell>
            </TableRow>
          ))}
          </TableBody>
        </Table>
        <Typography><strong>Advice:</strong> {consultation.advice}</Typography>
        <Typography sx={{mt:3}}><strong>Doctor:</strong> {consultation.doctor}</Typography>
        <Divider sx={{my:3}}/>
        <Box className="no-print" sx={{display:"flex",justifyContent:"space-between"}}>
          <Button variant="outlined" onClick={()=>navigate("/history/"+mobile)}>Back</Button>
          <Button variant="contained" onClick={handlePrint}>Download / Print PDF</Button>
        </Box>
      </Paper>
    </Container>
  );
}
